/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.calculadora;

/**
 *
 * @author Aluno
 */
public class OrcamentoViabilidade extends javax.swing.JFrame {

    /**
     * Creates new form OrcamentoViabilidade
     */
    public OrcamentoViabilidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        potlamp = new javax.swing.JTextField();
        qntlamp = new javax.swing.JTextField();
        metro = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        btnsimular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orcamento = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lbl1.setText("Nome da sua empresa:");

        lbl2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lbl2.setText("Quantidade de lâmpadas:");

        lbl4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lbl4.setText("Horário de funcionamento:");

        lbl5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lbl5.setText("Metros²:");

        lbl3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lbl3.setText("Potência das lâmpadas:");

        potlamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potlampActionPerformed(evt);
            }
        });

        qntlamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qntlampActionPerformed(evt);
            }
        });

        metro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroActionPerformed(evt);
            }
        });

        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });

        btnsimular.setBackground(new java.awt.Color(51, 153, 0));
        btnsimular.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnsimular.setText("Simular Orçamento");
        btnsimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimularActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Pictures\\ofc.PNG")); // NOI18N
        jLabel1.setText("jLabel1");

        orcamento.setColumns(20);
        orcamento.setRows(5);
        jScrollPane2.setViewportView(orcamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl1)
                                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qntlamp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl4)
                                    .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(potlamp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(metro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnsimular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qntlamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potlamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5)
                    .addComponent(metro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnsimular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void potlampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potlampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potlampActionPerformed

    private void qntlampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qntlampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qntlampActionPerformed

    private void metroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metroActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaActionPerformed

    private void btnsimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimularActionPerformed
       //Pegando o nome 
        String nomeTexto = nome.getText();
        
        //Pegando a quantidade de lâmpadas e transformando em double
        String qntTexto = qntlamp.getText();
        Double qntNumero = Double.valueOf(qntTexto);
        
       //Pegando a potencia das lâmpadas e transformando em double
       String potenciaTexto = potlamp.getText();
       Double potenciaNumero = Double.valueOf(potenciaTexto);
       
       //Pegando quantas horas o estabelecimento fica aberto e transformando em double
       String horarioTexto = hora.getText();
       Double horarioNumero = Double.valueOf(horarioTexto);
       
       //Pegando quantos metros tem o estabelecimento e transformando em Double 
       String metrosTexto = metro.getText();
       Double metrosNumero = Double.valueOf(metrosTexto);
       
       //Contas 
       
       Double tubo = (metrosNumero * 0.8) / 25;
       Double sensor = tubo;
       
       Double calculoWatts = qntNumero * potenciaNumero;
       Double calculoKwatts = calculoWatts / 1000;
       
       Double calculoDia = calculoKwatts * horarioNumero;
       Double calculoMes = calculoDia * 30;
       Double calculoAno = calculoMes * 12;
       
       Double valorMes = calculoMes * 0.516;
       Double valorAno = calculoAno * 0.516;
       
       Double descontoMes = valorMes * 0.40;
       Double descontoAno = valorAno * 0.40;
       
       Double valorTubo = tubo * 1000;
       Double valorSensor = sensor * 150;
       
       Double investimento = valorTubo + valorSensor;
       Double retorno = investimento / descontoAno;
       
       
       orcamento.setText(String.format("A empresa: %s gasta R$: %.2f por mês e \n R$: %.2f por ano. "
               + "\nCom esse projeto a empresa irá economizar cerca de \n R$: %.2f "
               + "(até 40%% de economia) por mês,\n e R$: %.2f por ano. \n "
               + "O investimento será de R$: %.2f. \n Esse valor lhe trará lucro a"
               + "partir do %.0f ° ano.", nomeTexto,valorMes,valorAno,descontoMes,
               descontoAno,investimento,retorno));
       
       
       

                                                         

       
       

       
       
       
       
               
           
       
       
               
               
       
       
       
       
       
       
       
       
       
       
        
        
        
        
        
        
    }//GEN-LAST:event_btnsimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrcamentoViabilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrcamentoViabilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrcamentoViabilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrcamentoViabilidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrcamentoViabilidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsimular;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JTextField metro;
    private javax.swing.JTextField nome;
    private javax.swing.JTextArea orcamento;
    private javax.swing.JTextField potlamp;
    private javax.swing.JTextField qntlamp;
    // End of variables declaration//GEN-END:variables
}
